version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    links:
      - rabbitmq:rabbitmq
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
    volumes_from:
      - app
    ports:
      - 8080:80
    depends_on:
      - app

  database:
      image: mysql:5.6
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        MYSQL_DATABASE: "table_db"
        MYSQL_ROOT_PASSWORD: "root"
      ports:
          - "33061:3306"
  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  dbdata: